import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sohne = localFont({
  src: [
    {
      path: "./fonts/Sohne Font/WOFF2/soehne-buch.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Sohne Font/WOFF2/soehne-buch-kursiv.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-sohne",
  fallback: ["Arial", "Helvetica", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sohne.variable} antialiased`}>{children}</body>
    </html>
  );
}
